# Modelo de secrets para Streamlit Cloud
# Cole este conteúdo na aba "Secrets" do projeto na nuvem

DATABASE_URL = "postgresql+psycopg://postgres:LuluJojo1011%23@db.erdwrlrucdkgolfrqsag.supabase.co:5432/postgres?sslmode=require"








