# Modelo de secrets para Streamlit Cloud
# Cole este conteúdo na aba "Secrets" do projeto na nuvem

DATABASE_URL = "postgresql+psycopg://postgres.erdwrlrucdkgolfrqsag:LuluJojo1011%23@aws-1-us-east-2.pooler.supabase.com:6543/postgres?sslmode=require"













